version: "3.9"

services:
  prometheus:
    image: "prom/prometheus:v2.31.1"
    command:
      - "--config.file"
      - "/etc/prometheus/config.yaml"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus"
  alertmanager:
    image: "prom/alertmanager:v0.21.0"
    ports:
      - "9093:9093"
  grafana:
    image: "grafana/grafana:7.4.5"
    command:
      - "--config"
      - "/etc/grafana/config.ini"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana:/etc/grafana"
  metrics_generator:
    image: "francescomari/metrics-generator:0.1.0"
    ports:
      - "8080:8080"
    command:
      - "-request-rate"
      - "1"
      - "-max-duration"
      - "10"
      - "-errors-percentage"
      - "10"
