version: "3.9"

services:
  prometheus:
    image: "prom/prometheus:v2.45.0"
    command:
      - "--config.file"
      - "/etc/prometheus/config.yaml"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus"
  alertmanager:
    image: "prom/alertmanager:v0.23.0"
    ports:
      - "9093:9093"
  grafana:
    image: "grafana/grafana:8.3.1"
    command:
      - "--config"
      - "/etc/grafana/config.ini"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana:/etc/grafana"
  metrics_generator:
    image: "francescomari/metrics-generator:0.2.0"
    ports:
      - "8080:8080"
