{
 "title": "Metrics Generator - RED",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "The rate of requests received, in req/s.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(metrics_generator_request_duration_seconds_count[5m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "The proportion of failed request, expressed as a percentage of the total requests received.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(metrics_generator_request_errors_count[5m]) / rate(metrics_generator_request_duration_seconds_count[5m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "description": "The duration of every request, expressed in seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(metrics_generator_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}